# Generated by Django 5.1.4 on 2025-01-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_qr_code_alter_pet_profile_picture_petcardphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='pets', to='pets.petphoto'),
        ),
        migrations.DeleteModel(
            name='PetCardPhoto',
        ),
    ]
