# Generated by Django 5.1.4 on 2025-01-15 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_petphoto_pet_photos_delete_petcardphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='photos',
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_image', models.ImageField(upload_to='medical_reports/')),
                ('description', models.TextField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pets.pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='medical_reports',
            field=models.ManyToManyField(blank=True, related_name='pets', to='pets.medicalreport'),
        ),
        migrations.DeleteModel(
            name='PetPhoto',
        ),
    ]
