# Generated by Django 5.1.4 on 2025-01-18 04:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_remove_pet_photos_medicalreport_pet_medical_reports_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='medical_reports',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='report_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='initial_medical_report',
            field=models.ImageField(blank=True, null=True, upload_to='initial_medical_reports/'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='pets.pet'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='report_image',
            field=models.ImageField(blank=True, null=True, upload_to='medical_reports/'),
        ),
    ]
