# Generated by Django 5.1.4 on 2025-01-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_remove_medicalreport_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='initial_medical_report',
        ),
    ]
